image: nixos/unstable
packages:
  - nixos.curl
  - nixos.emmylua-check
  - nixos.neovim
  - nixos.jq
sources:
  - https://git.sr.ht/~chinmay/clangd_extensions.nvim
tasks:
  - lint: |
      cd clangd_extensions.nvim
      nvim_runtime="$(nvim --clean --headless -c 'echo $VIMRUNTIME' -c 'q' 2>&1)/lua/"
      wcurl https://raw.githubusercontent.com/neovim/neovim/a8361c3afc5b9281814e9f16a9d4291e095b38fa/runtime/lua/uv/_meta.lua
      sudo mv _meta.lua "$nvim_runtime/uv/"
      jq --arg lib "$nvim_runtime" '.workspace.library = [$lib]' .emmyrc.json > .emmyrc.ci.json
      mv .emmyrc.ci.json .emmyrc.json
      emmylua_check --warnings-as-errors .
