image: nixos/unstable
packages:
  - nixos.neovim
  - nixos.jq
sources:
  - https://git.sr.ht/~chinmay/clangd_extensions.nvim
tasks:
  - format: |
      cd clangd_extensions.nvim
      nix develop --extra-experimental-features "nix-command flakes" -c stylua --check .
  - lint: |
      cd clangd_extensions.nvim
      nvim_runtime="$(nvim --clean --headless -c 'echo $VIMRUNTIME' -c 'q' 2>&1)/lua/"
      jq --arg rt "$nvim_runtime" '.workspace.library = [$rt, "lua/"]' .emmyrc.json > .emmyrc.ci.json
      mv .emmyrc.ci.json .emmyrc.json
      nix develop --extra-experimental-features "nix-command flakes" -c emmylua_check --warnings-as-errors .
